#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 02:17 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.UspsStates.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/usps_states/2.0", TypeName="USStateCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/usps_states/2.0", IsNullable=false, ElementName="USStateCodeSimpleType")]
    public enum USStateCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AA")]
        AA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AE")]
        AE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AK")]
        AK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AL")]
        AL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AP")]
        AP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AR")]
        AR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AS")]
        AS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AZ")]
        AZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CA")]
        CA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CO")]
        CO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CT")]
        CT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DC")]
        DC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DE")]
        DE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FL")]
        FL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FM")]
        FM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GA")]
        GA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GU")]
        GU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HI")]
        HI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IA")]
        IA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ID")]
        ID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IL")]
        IL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IN")]
        IN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KS")]
        KS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KY")]
        KY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LA")]
        LA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MA")]
        MA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MD")]
        MD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ME")]
        ME,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MH")]
        MH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MI")]
        MI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MN")]
        MN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MO")]
        MO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MP")]
        MP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MS")]
        MS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MT")]
        MT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NC")]
        NC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ND")]
        ND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NE")]
        NE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NH")]
        NH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NJ")]
        NJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NM")]
        NM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NV")]
        NV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NY")]
        NY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OH")]
        OH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OK")]
        OK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OR")]
        OR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PA")]
        PA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PR")]
        PR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PW")]
        PW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RI")]
        RI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SC")]
        SC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SD")]
        SD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TN")]
        TN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TX")]
        TX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UT")]
        UT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VA")]
        VA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VI")]
        VI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VT")]
        VT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WA")]
        WA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WI")]
        WI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WV")]
        WV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WY")]
        WY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/usps_states/2.0", TypeName="USStateCodeType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/usps_states/2.0", IsNullable=true, ElementName="USStateCodeType")]
    
    public partial class USStateCodeType : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private USStateCodeSimpleType value;
        
        public USStateCodeType()
        {
        }
        
        public USStateCodeType(string id, string metadata, string linkMetadata, USStateCodeSimpleType value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public USStateCodeSimpleType Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
}
