#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 02:41 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.Iso4217.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/iso_4217/2.0", TypeName="CurrencyCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/iso_4217/2.0", IsNullable=false, ElementName="CurrencyCodeSimpleType")]
    public enum CurrencyCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ADP")]
        ADP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AED")]
        AED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AFA")]
        AFA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ALL")]
        ALL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AMD")]
        AMD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ANG")]
        ANG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AON")]
        AON,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AOR")]
        AOR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ARS")]
        ARS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ATS")]
        ATS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AUD")]
        AUD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AWG")]
        AWG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AZM")]
        AZM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BAM")]
        BAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BBD")]
        BBD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BDT")]
        BDT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BEF")]
        BEF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BGL")]
        BGL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BGN")]
        BGN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BHD")]
        BHD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BIF")]
        BIF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BMD")]
        BMD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BND")]
        BND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BRL")]
        BRL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BSD")]
        BSD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BTN")]
        BTN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BWP")]
        BWP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BYR")]
        BYR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BZD")]
        BZD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CAD")]
        CAD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CDF")]
        CDF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CHF")]
        CHF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CLF")]
        CLF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CLP")]
        CLP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CNY")]
        CNY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="COP")]
        COP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CRC")]
        CRC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CUP")]
        CUP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CVE")]
        CVE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CYP")]
        CYP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CZK")]
        CZK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DEM")]
        DEM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DJF")]
        DJF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DKK")]
        DKK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DOP")]
        DOP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DZD")]
        DZD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ECS")]
        ECS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ECV")]
        ECV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EEK")]
        EEK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EGP")]
        EGP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ERN")]
        ERN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ESP")]
        ESP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ETB")]
        ETB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EUR")]
        EUR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FIM")]
        FIM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FJD")]
        FJD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FKP")]
        FKP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FRF")]
        FRF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GBP")]
        GBP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GEL")]
        GEL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GHC")]
        GHC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GIP")]
        GIP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GMD")]
        GMD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GNF")]
        GNF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GRD")]
        GRD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GTQ")]
        GTQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GWP")]
        GWP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GYD")]
        GYD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HKD")]
        HKD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HNL")]
        HNL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HRK")]
        HRK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HTG")]
        HTG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HUF")]
        HUF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IDR")]
        IDR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IEP")]
        IEP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ILS")]
        ILS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="INR")]
        INR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IQD")]
        IQD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IRR")]
        IRR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ISK")]
        ISK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ITL")]
        ITL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JMD")]
        JMD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JOD")]
        JOD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JPY")]
        JPY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KES")]
        KES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KGS")]
        KGS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KHR")]
        KHR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KMF")]
        KMF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KPW")]
        KPW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KRW")]
        KRW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KWD")]
        KWD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KYD")]
        KYD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KZT")]
        KZT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LAK")]
        LAK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LBP")]
        LBP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LKR")]
        LKR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LRD")]
        LRD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LSL")]
        LSL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LTL")]
        LTL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LUF")]
        LUF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LVL")]
        LVL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LYD")]
        LYD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MAD")]
        MAD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MDL")]
        MDL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MGF")]
        MGF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MKD")]
        MKD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MMK")]
        MMK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MNT")]
        MNT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MOP")]
        MOP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MRO")]
        MRO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MTL")]
        MTL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MUR")]
        MUR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MVR")]
        MVR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MWK")]
        MWK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MXN")]
        MXN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MXV")]
        MXV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MYR")]
        MYR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MZM")]
        MZM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NAD")]
        NAD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NGN")]
        NGN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NIO")]
        NIO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NLG")]
        NLG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NOK")]
        NOK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NPR")]
        NPR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NZD")]
        NZD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OMR")]
        OMR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PAB")]
        PAB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PEN")]
        PEN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PGK")]
        PGK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PHP")]
        PHP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PKR")]
        PKR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PLN")]
        PLN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PTE")]
        PTE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PYG")]
        PYG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="QAR")]
        QAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ROL")]
        ROL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RUB")]
        RUB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RUR")]
        RUR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RWF")]
        RWF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SAR")]
        SAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SBD")]
        SBD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SCR")]
        SCR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SDD")]
        SDD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SEK")]
        SEK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SGD")]
        SGD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SHP")]
        SHP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SIT")]
        SIT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SKK")]
        SKK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SLL")]
        SLL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SOS")]
        SOS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SRG")]
        SRG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="STD")]
        STD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SVC")]
        SVC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SYP")]
        SYP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SZL")]
        SZL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="THB")]
        THB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TJR")]
        TJR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TJS")]
        TJS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TMM")]
        TMM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TND")]
        TND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TOP")]
        TOP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TPE")]
        TPE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TRL")]
        TRL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TTD")]
        TTD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TWD")]
        TWD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TZS")]
        TZS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UAH")]
        UAH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UGX")]
        UGX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="USD")]
        USD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="USN")]
        USN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="USS")]
        USS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UYU")]
        UYU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UZS")]
        UZS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VEB")]
        VEB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VND")]
        VND,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VUV")]
        VUV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WST")]
        WST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XAF")]
        XAF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XAG")]
        XAG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XAU")]
        XAU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XBA")]
        XBA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XBB")]
        XBB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XBC")]
        XBC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XBD")]
        XBD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XCD")]
        XCD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XDR")]
        XDR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XFO")]
        XFO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XFU")]
        XFU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XOF")]
        XOF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XPD")]
        XPD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XPF")]
        XPF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XPT")]
        XPT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XTS")]
        XTS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="XXX")]
        XXX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="YER")]
        YER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="YUM")]
        YUM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZAL")]
        ZAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZAR")]
        ZAR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZMK")]
        ZMK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZRN")]
        ZRN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZWD")]
        ZWD,
    }
}
