#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 02:12 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.AnsiD20.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="DriverLicenseClassCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=false, ElementName="DriverLicenseClassCodeSimpleType")]
    public enum DriverLicenseClassCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="A")]
        A,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="B")]
        B,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="C")]
        C,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="M")]
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="DriverLicenseClassCodeType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=true, ElementName="DriverLicenseClassCodeType")]
    
    public partial class DriverLicenseClassCodeType : object
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private DriverLicenseClassCodeSimpleType value;
        
        public DriverLicenseClassCodeType()
        {
        }
        
        public DriverLicenseClassCodeType(string id, string metadata, string linkMetadata, DriverLicenseClassCodeSimpleType value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public DriverLicenseClassCodeSimpleType Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="DrivingRestrictionCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=false, ElementName="DrivingRestrictionCodeSimpleType")]
    public enum DrivingRestrictionCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="B")]
        B,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="C")]
        C,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="D")]
        D,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="E")]
        E,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="F")]
        F,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="G")]
        G,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="I")]
        I,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="J")]
        J,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="K")]
        K,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="L")]
        L,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="O")]
        O,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="W")]
        W,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="DrivingRestrictionCodeType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=true, ElementName="DrivingRestrictionCodeType")]
    
    public partial class DrivingRestrictionCodeType : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private DrivingRestrictionCodeSimpleType value;
        
        public DrivingRestrictionCodeType()
        {
        }
        
        public DrivingRestrictionCodeType(string id, string metadata, string linkMetadata, DrivingRestrictionCodeSimpleType value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public DrivingRestrictionCodeSimpleType Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="HazMatCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=false, ElementName="HazMatCodeSimpleType")]
    public enum HazMatCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", TypeName="HazMatCodeType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/ansi_d20/2.0", IsNullable=true, ElementName="HazMatCodeType")]
    
    public partial class HazMatCodeType : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private HazMatCodeSimpleType value;
        
        public HazMatCodeType()
        {
        }
        
        public HazMatCodeType(string id, string metadata, string linkMetadata, HazMatCodeSimpleType value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public HazMatCodeSimpleType Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
}
