#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 12-09-08 03:17 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.AppInfo.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0", TypeName="Resource")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false, ElementName="Resource")]
    
    public partial class Resource : object 
    {
        
        /// <remarks/>
        private string name;
        
        public Resource()
        {
        }
        
        public Resource(string name)
        {
            this.name = name;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName", AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0", TypeName="Deprecated")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false, ElementName="Deprecated")]
    
    public partial class Deprecated : object 
    {
        
        /// <remarks/>
        private bool value;
        
        public Deprecated()
        {
        }
        
        public Deprecated(bool value)
        {
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, AttributeName="value")]
        public bool Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0", TypeName="Base")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false, ElementName="Base")]
    
    public partial class Base : object 
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string @namespace;
        
        public Base()
        {
        }
        
        public Base(string name, string @namespace)
        {
            this.name = name;
            this.@namespace = @namespace;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName", AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="namespace")]
        public string Namespace
        {
            get
            {
                return this.@namespace;
            }
            set
            {
                if ((this.@namespace != value))
                {
                    this.@namespace = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0", TypeName="ReferenceTarget")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false, ElementName="ReferenceTarget")]
    
    public partial class ReferenceTarget : object 
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string @namespace;
        
        public ReferenceTarget()
        {
        }
        
        public ReferenceTarget(string name, string @namespace)
        {
            this.name = name;
            this.@namespace = @namespace;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName", AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="namespace")]
        public string Namespace
        {
            get
            {
                return this.@namespace;
            }
            set
            {
                if ((this.@namespace != value))
                {
                    this.@namespace = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://niem.gov/niem/appinfo/2.0", TypeName="AppliesTo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/appinfo/2.0", IsNullable=false, ElementName="AppliesTo")]
    
    public partial class AppliesTo : object 
    {
        
        /// <remarks/>
        private string name;
        
        /// <remarks/>
        private string @namespace;
        
        public AppliesTo()
        {
        }
        
        public AppliesTo(string name, string @namespace)
        {
            this.name = name;
            this.@namespace = @namespace;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="NCName", AttributeName="name")]
        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
                if ((this.name != value))
                {
                    this.name = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="namespace")]
        public string Namespace
        {
            get
            {
                return this.@namespace;
            }
            set
            {
                if ((this.@namespace != value))
                {
                    this.@namespace = value;
                }
            }
        }
        
    }
}
