#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 02:26 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.Proxy.xsd.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="anyURI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="anyURI")]
    
    public partial class AnyURI : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private string value;
        
        public AnyURI()
        {
        }
        
        public AnyURI(string id, string metadata, string linkMetadata, string value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="base64Binary")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="base64Binary")]
    
    public partial class Base64Binary : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private byte[] value;
        
        public Base64Binary()
        {
        }

        public Base64Binary(byte[] value)
        {
            this.value = value; 
        }

        public Base64Binary(string id, string metadata, string linkMetadata, byte[] value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="boolean")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="boolean")]
    
    public partial class Boolean : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private bool value;
        
        public Boolean()
        {
        }

        public Boolean(System.Boolean value)
        {
            this.value = value; 
        }

        
        public Boolean(string id, string metadata, string linkMetadata, bool value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="date")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="date")]
    
    public partial class Date : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private System.DateTime value;
        
        public Date()
        {
        }

        public Date(System.DateTime value)
        {
            this.value = value; 
        }

        
        public Date(string id, string metadata, string linkMetadata, System.DateTime value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="dateTime")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="dateTime")]
    
    public partial class DateTime : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private System.DateTime value;
        
        public DateTime()
        {
        }

        public DateTime(System.DateTime value)
        {
            this.value = value;
        }

        public DateTime(string id, string metadata, string linkMetadata, System.DateTime value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute(DataType = "dateTime")]
        public System.DateTime Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="decimal")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="decimal")]
    
    public partial class Decimal : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private decimal value;
        
        public Decimal()
        {
        }

        public Decimal(decimal value)
        {
            this.value = value ;
        }

        public Decimal(string id, string metadata, string linkMetadata, decimal value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="duration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="duration")]
    
    public partial class Duration : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private string value;
        
        public Duration()
        {
        }
        public Duration(string value)
        {
            this.value = value; 
        }
        
        public Duration(string id, string metadata, string linkMetadata, string value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="duration")]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="gYear")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="gYear")]
    
    public partial class GYear : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private string value;
        
        public GYear()
        {
        }
        public GYear(string value)
        {
            this.value = value; 
        }
        
        public GYear(string id, string metadata, string linkMetadata, string value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="gYear")]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="string")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="string")]
    
    public partial class String : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private string value;
        
        public String()
        {
        }
        public String(string value)
        {
            this.value = value; 
        }
        
        public String(string id, string metadata, string linkMetadata, string value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }

        public override string ToString()
        {
            return !string.IsNullOrEmpty(this.value) ? this.value: string.Empty;
        }

        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", TypeName="time")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/proxy/xsd/2.0", IsNullable=true, ElementName="time")]
    
    public partial class Time : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private System.DateTime value;
        
        public Time()
        {
        }
        public Time(System.DateTime value)
        {
            this.value = value; 
        }
        
        public Time(string id, string metadata, string linkMetadata, System.DateTime value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="time")]
        public System.DateTime Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
}
