#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 06:06 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Niem.Structures.v20;
using Niem.Proxy.xsd.v20;
using Niem.NiemCore.v20;
namespace Niem.Domains.Screeing.v20
{
    
    
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/domains/screening/2.0", TypeName="MarriageAssociationAugmentationType")]
    [System.Xml.Serialization.XmlRootAttribute("MarriageAssociationAugmentation", Namespace="http://niem.gov/niem/domains/screening/2.0", IsNullable=false, ElementName="MarriageAssociationAugmentationType")]
    
    public partial class MarriageAssociationAugmentationType : AugmentationType
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<Boolean> divorceDecreeIndicator;
        
        /// <remarks/>
        private System.Collections.Generic.List<TextType> marriageCityName;
        
        public MarriageAssociationAugmentationType()
        {
        }
        
        public MarriageAssociationAugmentationType(System.Collections.Generic.List<Boolean> divorceDecreeIndicator, System.Collections.Generic.List<TextType> marriageCityName)
        {
            this.divorceDecreeIndicator = divorceDecreeIndicator;
            this.marriageCityName = marriageCityName;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DivorceDecreeIndicator", IsNullable=true, Order=0)]
        public System.Collections.Generic.List<Boolean> DivorceDecreeIndicator
        {
            get
            {
                return this.divorceDecreeIndicator;
            }
            set
            {
                if ((this.divorceDecreeIndicator != value))
                {
                    this.divorceDecreeIndicator = value;
                    this.RaisePropertyChanged("DivorceDecreeIndicator");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("MarriageCityName", IsNullable=true, Order=1)]
        public System.Collections.Generic.List<TextType> MarriageCityName
        {
            get
            {
                return this.marriageCityName;
            }
            set
            {
                if ((this.marriageCityName != value))
                {
                    this.marriageCityName = value;
                    this.RaisePropertyChanged("MarriageCityName");
                }
            }
        }
    }
    
    
}
