#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 02:37 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Niem.Fips104.v20
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/fips_10-4/2.0", TypeName="CountryCodeSimpleType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/fips_10-4/2.0", IsNullable=false, ElementName="CountryCodeSimpleType")]
    public enum CountryCodeSimpleType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AA")]
        AA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AC")]
        AC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AE")]
        AE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AF")]
        AF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AG")]
        AG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AJ")]
        AJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AL")]
        AL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AM")]
        AM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AN")]
        AN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AO")]
        AO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AQ")]
        AQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AR")]
        AR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AS")]
        AS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AT")]
        AT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AU")]
        AU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AV")]
        AV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="AY")]
        AY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BA")]
        BA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BB")]
        BB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BC")]
        BC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BD")]
        BD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BE")]
        BE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BF")]
        BF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BG")]
        BG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BH")]
        BH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BK")]
        BK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BL")]
        BL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BM")]
        BM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BN")]
        BN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BO")]
        BO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BP")]
        BP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BQ")]
        BQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BR")]
        BR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BS")]
        BS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BT")]
        BT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BU")]
        BU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BV")]
        BV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BX")]
        BX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="BY")]
        BY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CA")]
        CA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CB")]
        CB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CD")]
        CD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CE")]
        CE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CF")]
        CF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CG")]
        CG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CH")]
        CH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CI")]
        CI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CJ")]
        CJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CK")]
        CK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CM")]
        CM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CN")]
        CN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CO")]
        CO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CQ")]
        CQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CR")]
        CR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CS")]
        CS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CT")]
        CT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CU")]
        CU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CV")]
        CV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CW")]
        CW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="CY")]
        CY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DA")]
        DA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DJ")]
        DJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DO")]
        DO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DQ")]
        DQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="DR")]
        DR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EC")]
        EC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EG")]
        EG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EI")]
        EI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EK")]
        EK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EN")]
        EN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ER")]
        ER,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ES")]
        ES,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ET")]
        ET,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EU")]
        EU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="EZ")]
        EZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FG")]
        FG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FI")]
        FI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FJ")]
        FJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FK")]
        FK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FM")]
        FM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FO")]
        FO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FP")]
        FP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FQ")]
        FQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FR")]
        FR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="FS")]
        FS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GA")]
        GA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GB")]
        GB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GG")]
        GG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GH")]
        GH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GI")]
        GI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GJ")]
        GJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GK")]
        GK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GL")]
        GL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GM")]
        GM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GO")]
        GO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GP")]
        GP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GQ")]
        GQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GR")]
        GR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GT")]
        GT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GV")]
        GV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GY")]
        GY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="GZ")]
        GZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HA")]
        HA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HK")]
        HK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HM")]
        HM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HO")]
        HO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HQ")]
        HQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HR")]
        HR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="HU")]
        HU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IC")]
        IC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ID")]
        ID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IM")]
        IM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IN")]
        IN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IO")]
        IO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IP")]
        IP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IR")]
        IR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IS")]
        IS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IT")]
        IT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IV")]
        IV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="IZ")]
        IZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JA")]
        JA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JE")]
        JE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JM")]
        JM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JN")]
        JN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JO")]
        JO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JQ")]
        JQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="JU")]
        JU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KE")]
        KE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KG")]
        KG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KN")]
        KN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KQ")]
        KQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KR")]
        KR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KS")]
        KS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KT")]
        KT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KU")]
        KU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KZ")]
        KZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LA")]
        LA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LE")]
        LE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LG")]
        LG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LH")]
        LH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LI")]
        LI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LO")]
        LO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LQ")]
        LQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LS")]
        LS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LT")]
        LT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LU")]
        LU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="LY")]
        LY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MA")]
        MA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MB")]
        MB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MC")]
        MC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MD")]
        MD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MF")]
        MF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MG")]
        MG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MH")]
        MH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MI")]
        MI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MJ")]
        MJ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MK")]
        MK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ML")]
        ML,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MN")]
        MN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MO")]
        MO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MP")]
        MP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MQ")]
        MQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MR")]
        MR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MT")]
        MT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MU")]
        MU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MV")]
        MV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MX")]
        MX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MY")]
        MY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MZ")]
        MZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NC")]
        NC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NE")]
        NE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NF")]
        NF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NG")]
        NG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NH")]
        NH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NI")]
        NI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NL")]
        NL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NM")]
        NM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NO")]
        NO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NP")]
        NP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NR")]
        NR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NS")]
        NS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NT")]
        NT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NU")]
        NU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="NZ")]
        NZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="OS")]
        OS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PA")]
        PA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PC")]
        PC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PE")]
        PE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PF")]
        PF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PG")]
        PG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PK")]
        PK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PL")]
        PL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PM")]
        PM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PO")]
        PO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PP")]
        PP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PS")]
        PS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PU")]
        PU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="QA")]
        QA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RB")]
        RB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RE")]
        RE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RM")]
        RM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RO")]
        RO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RP")]
        RP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RQ")]
        RQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RS")]
        RS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RW")]
        RW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SA")]
        SA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SB")]
        SB,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SC")]
        SC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SE")]
        SE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SF")]
        SF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SG")]
        SG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SH")]
        SH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SI")]
        SI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SL")]
        SL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SM")]
        SM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SN")]
        SN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SO")]
        SO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SP")]
        SP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ST")]
        ST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SU")]
        SU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SV")]
        SV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SW")]
        SW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SX")]
        SX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SY")]
        SY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SZ")]
        SZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TD")]
        TD,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TE")]
        TE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TH")]
        TH,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TI")]
        TI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TK")]
        TK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TL")]
        TL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TN")]
        TN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TO")]
        TO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TP")]
        TP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TS")]
        TS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TT")]
        TT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TU")]
        TU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TV")]
        TV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TW")]
        TW,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TX")]
        TX,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="TZ")]
        TZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UF")]
        UF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UG")]
        UG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UK")]
        UK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UP")]
        UP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="US")]
        US,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UV")]
        UV,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UY")]
        UY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="UZ")]
        UZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VC")]
        VC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VE")]
        VE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VI")]
        VI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VM")]
        VM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VQ")]
        VQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="VT")]
        VT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WA")]
        WA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WE")]
        WE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WF")]
        WF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WI")]
        WI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WQ")]
        WQ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WS")]
        WS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="WZ")]
        WZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="YM")]
        YM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZA")]
        ZA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="ZI")]
        ZI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://niem.gov/niem/fips_10-4/2.0", TypeName="CountryCodeType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://niem.gov/niem/fips_10-4/2.0", IsNullable=true, ElementName="CountryCodeType")]
    
    public partial class CountryCodeType : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string metadata;
        
        /// <remarks/>
        private string linkMetadata;
        
        /// <remarks/>
        private CountryCodeSimpleType value;
        
        public CountryCodeType()
        {
        }
        
        public CountryCodeType(string id, string metadata, string linkMetadata, CountryCodeSimpleType value)
        {
            this.id = id;
            this.metadata = metadata;
            this.linkMetadata = linkMetadata;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="ID", AttributeName="id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="metadata")]
        public string Metadata
        {
            get
            {
                return this.metadata;
            }
            set
            {
                if ((this.metadata != value))
                {
                    this.metadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://niem.gov/niem/structures/2.0", DataType="IDREFS", AttributeName="linkMetadata")]
        public string LinkMetadata
        {
            get
            {
                return this.linkMetadata;
            }
            set
            {
                if ((this.linkMetadata != value))
                {
                    this.linkMetadata = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public CountryCodeSimpleType Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
}
