/*
	'=======================================================================
	'   Author(s):      D V Rao
	'   Module/Form:    ECF-4.0-CaseListQueryMessage.cs
	'   Created Date:   
	'   Description:    
	'
	'   Modification History:
	'=======================================================================
	'   Author(s)       Date        Control/Procedure       Change
	'=======================================================================
    '   Rao     04/24/2012       Moved AddNameSpaces to EcfHelper
	'=======================================================================
	*/

#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 09:59 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.NiemCore.v20;
using Niem.Structures.v20;

namespace Oasis.LegalXml.CourtFiling.v40.CaseListQuery
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListQueryMessage-4.0", TypeName = "CaseListQueryMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("CaseListQueryMessage", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListQueryMessage-4.0", IsNullable = false, ElementName = "CaseListQueryMessageType")]
    
    public partial class CaseListQueryMessageType : QueryMessageType
    {

        /// <remarks/>
        private System.Collections.Generic.List<CaseType> caseListQueryCase;

        /// <remarks/>
        private System.Collections.Generic.List<DateRangeType> caseListQueryTimeRange;

        /// <remarks/>
        private System.Collections.Generic.List<CaseParticipantType> caseListQueryCaseParticipant;

        [field: System.NonSerialized]
        [System.Xml.Serialization.XmlNamespaceDeclarations]
        public System.Xml.Serialization.XmlSerializerNamespaces namespaces = new System.Xml.Serialization.XmlSerializerNamespaces(); 

        public CaseListQueryMessageType()
        {
            EcfHelper.AddNameSpaces(this.namespaces);
        }

        public CaseListQueryMessageType(System.Collections.Generic.List<CaseType> caseListQueryCase, System.Collections.Generic.List<DateRangeType> caseListQueryTimeRange, System.Collections.Generic.List<CaseParticipantType> caseListQueryCaseParticipant)
        {
            EcfHelper.AddNameSpaces(this.namespaces);
            this.caseListQueryCase = caseListQueryCase;
            this.caseListQueryTimeRange = caseListQueryTimeRange;
            this.caseListQueryCaseParticipant = caseListQueryCaseParticipant;
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseListQueryCase", Order = 0)]
        public System.Collections.Generic.List<CaseType> CaseListQueryCase
        {
            get
            {
                return this.caseListQueryCase;
            }
            set
            {
                if ((this.caseListQueryCase != value))
                {
                    this.caseListQueryCase = value;
                    this.RaisePropertyChanged("CaseListQueryCase");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseListQueryTimeRange", Order = 1)]
        public System.Collections.Generic.List<DateRangeType> CaseListQueryTimeRange
        {
            get
            {
                return this.caseListQueryTimeRange;
            }
            set
            {
                if ((this.caseListQueryTimeRange != value))
                {
                    this.caseListQueryTimeRange = value;
                    this.RaisePropertyChanged("CaseListQueryTimeRange");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseListQueryCaseParticipant", Order = 2)]
        public System.Collections.Generic.List<CaseParticipantType> CaseListQueryCaseParticipant
        {
            get
            {
                return this.caseListQueryCaseParticipant;
            }
            set
            {
                if ((this.caseListQueryCaseParticipant != value))
                {
                    this.caseListQueryCaseParticipant = value;
                    this.RaisePropertyChanged("CaseListQueryCaseParticipant");
                }
            }
        }


    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListQueryMessage-4.0", TypeName = "CaseParticipantType")]
    [System.Xml.Serialization.XmlRootAttribute("CaseListQueryCaseParticipant", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListQueryMessage-4.0", IsNullable = false, ElementName = "CaseParticipantType")]
    
    public partial class CaseParticipantType : ComplexObjectType
    {

        /// <remarks/>
        private Ecf.CaseParticipantType caseParticipant;
        private IdentificationType filingSubmissionSubmitterID;

        public CaseParticipantType()
        {
        }

        public CaseParticipantType(Ecf.CaseParticipantType caseParticipant, IdentificationType filingSubmissionSubmitterID)
        {
            this.caseParticipant = caseParticipant;
            this.filingSubmissionSubmitterID = filingSubmissionSubmitterID;
        }


        [System.Xml.Serialization.XmlElementAttribute("caseParticipant", Order = 0)]
        public Ecf.CaseParticipantType CaseParticipant
        {
            get
            {
                return this.caseParticipant;
            }
            set
            {
                if ((this.caseParticipant != value))
                {
                    this.caseParticipant = value;
                    this.RaisePropertyChanged("CaseParticipant");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("FilingSubmissionSubmitterID", Order = 1)]
        public IdentificationType FilingSubmissionSubmitterID
        {
            get
            {
                return this.filingSubmissionSubmitterID;
            }
            set
            {
                if ((this.filingSubmissionSubmitterID != value))
                {
                    this.filingSubmissionSubmitterID = value;
                    this.RaisePropertyChanged("FilingSubmissionSubmitterID");
                }
            }
        }

    }

}
