/*
	'=======================================================================
	'   Author(s):      D V Rao
	'   Module/Form:    ECF-4.0-CaseListResponseMessage.cs
	'   Created Date:   
	'   Description:    
	'
	'   Modification History:
	'=======================================================================
	'   Author(s)       Date        Control/Procedure       Change
	'=======================================================================
    '   Rao     04/24/2012       Cleaned up code. changed private property @case to make the code redable
    '   Rao     04/24/2012       Moved AddNameSpaces to EcfHelper
	'=======================================================================
	*/

#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 10:19 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.NiemCore.v20;
 
namespace Oasis.LegalXml.CourtFiling.v40.CaseListResponse
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListResponseMessage-4.0", TypeName="CaseListResponseMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("CaseListResponseMessage", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CaseListResponseMessage-4.0", IsNullable=false, ElementName="CaseListResponseMessageType")]
    
    public partial class CaseListResponseMessageType : QueryResponseMessageType
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<object> matchingCases;

        [field: System.NonSerialized]
        [System.Xml.Serialization.XmlNamespaceDeclarations]
        public System.Xml.Serialization.XmlSerializerNamespaces namespaces = new System.Xml.Serialization.XmlSerializerNamespaces(); 

        public CaseListResponseMessageType()
        {
            EcfHelper.AddNameSpaces(this.namespaces);
        }

        public CaseListResponseMessageType(System.Collections.Generic.List<object> matchingCases)
        {
            EcfHelper.AddNameSpaces(this.namespaces);
            this.matchingCases = matchingCases;
        }

        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Niem.NiemCore.v20.CaseType), Order = 0, Namespace = "http://niem.gov/niem/niem-core/2.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CitationCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Civil.CivilCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CivilCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Criminal.CriminalCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Domestic.DomesticCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Juvenile.JuvenileCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:JuvenileCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("AppellateCase", typeof(Oasis.LegalXml.CourtFiling.v40.Appellate.AppellateCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:AppellateCase-4.0", IsNullable = true)]
        public System.Collections.Generic.List<object> Case
        {
            get
            {
                return this.matchingCases;
            }
            set
            {
                if ((this.matchingCases != value))
                {
                    this.matchingCases = value;
                    this.RaisePropertyChanged("Case");
                }
            }
        }



    }
    
}
