/*
	'=======================================================================
	'   Author(s):      D V Rao
	'   Module/Form:    ECF-4.0-CoreFilingMessage.cs
	'   Created Date:   
	'   Description:    
	'
	'   Modification History:
	'=======================================================================
	'   Author(s)       Date        Control/Procedure       Change
 	'=======================================================================
    '   Rao     02/10/2015      Removed references to Amcad extensions
    '   Rao     04/24/2012       Cleaned up code. changed private property @case to make the code redable
    '   Rao     04/24/2012       Moved AddNameSpaces to EcfHelper
    '   Rao     08/12/2011       Added XML Serialization options for AppellateCase 
	'=======================================================================
	*/

#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 09:21 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Niem.NiemCore.v20;
using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.Proxy.xsd.v20; 

namespace Oasis.LegalXml.CourtFiling.v40.Core
{

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Appellate.AppellateCaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Civil.CivilCaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Criminal.CriminalCaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Domestic.DomesticCaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Oasis.LegalXml.CourtFiling.v40.Juvenile.JuvenileCaseType))]

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Niem.NiemCore.v20.CaseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CoreFilingMessage-4.0", TypeName="CoreFilingMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("CoreFilingMessage", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CoreFilingMessage-4.0", IsNullable=false, ElementName="CoreFilingMessage")]
    public partial class CoreFilingMessageType : ElectronicFilingMessageType
    {
        
        /// <remarks/>
        private object filingCase;
        private CaseTypeSelectionType caseTypeSelection; 
        
        /// <remarks/>
        private Boolean filingConfidentialityIndicator;
        
        /// <remarks/>
        private System.Collections.Generic.List<Ecf.DocumentType> filingLeadDocument;
        
        /// <remarks/>
        private System.Collections.Generic.List<Ecf.DocumentType> filingConnectedDocument;

        [field: System.NonSerialized]
        [System.Xml.Serialization.XmlNamespaceDeclarations]
        public System.Xml.Serialization.XmlSerializerNamespaces namespaces = new System.Xml.Serialization.XmlSerializerNamespaces(); 

        public CoreFilingMessageType()
        {
            EcfHelper.AddNameSpaces(namespaces);
        }

        public CoreFilingMessageType(object filingCase, CaseTypeSelectionType caseTypeSelection, Boolean filingConfidentialityIndicator, System.Collections.Generic.List<Ecf.DocumentType> filingLeadDocument, System.Collections.Generic.List<Ecf.DocumentType> filingConnectedDocument)
        {
            EcfHelper.AddNameSpaces(namespaces);
            this.filingCase = filingCase;
            this.caseTypeSelection = caseTypeSelection;
            this.filingConfidentialityIndicator = filingConfidentialityIndicator;
            this.filingLeadDocument = filingLeadDocument;
            this.filingConnectedDocument = filingConnectedDocument;
        }


        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Niem.NiemCore.v20.CaseType), Order = 0, Namespace = "http://niem.gov/niem/niem-core/2.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CitationCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Civil.CivilCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CivilCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Criminal.CriminalCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Domestic.DomesticCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Case", typeof(Oasis.LegalXml.CourtFiling.v40.Juvenile.JuvenileCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:JuvenileCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("AppellateCase", typeof(Oasis.LegalXml.CourtFiling.v40.Appellate.AppellateCaseType), Order = 0, Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:AppellateCase-4.0", IsNullable = true)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("CaseTypeSelection")]
        public object Case
        {
            get
            {
                return this.filingCase;
            }
            set
            {
                if ((this.filingCase != value))
                {
                    this.caseTypeSelection = EcfHelper.GetCaseTypeSelectionType(caseObject:value);
                    this.filingCase = value;
                    this.RaisePropertyChanged("Case");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseTypeSelection", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public CaseTypeSelectionType CaseTypeSelection
        {
            get
            {
                return this.caseTypeSelection;
            }
            set
            {
                if ((this.caseTypeSelection != value))
                {
                    this.caseTypeSelection = value;
                    this.RaisePropertyChanged("CaseTypeSelection");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="FilingConfidentialityIndicator")]
        public Boolean FilingConfidentialityIndicator
        {
            get
            {
                return this.filingConfidentialityIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("FilingConfidentialityIndicator");
                }
                if ((this.filingConfidentialityIndicator != value))
                {
                    this.filingConfidentialityIndicator = value;
                    this.RaisePropertyChanged("FilingConfidentialityIndicator");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FilingLeadDocument", Order=3)]
        public System.Collections.Generic.List<Ecf.DocumentType> FilingLeadDocument
        {
            get
            {
                return this.filingLeadDocument;
            }
            set
            {
                if ((this.filingLeadDocument != value))
                {
                    this.filingLeadDocument = value;
                    this.RaisePropertyChanged("FilingLeadDocument");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FilingConnectedDocument", Order=4)]
        public System.Collections.Generic.List<Ecf.DocumentType> FilingConnectedDocument
        {
            get
            {
                return this.filingConnectedDocument;
            }
            set
            {
                if ((this.filingConnectedDocument != value))
                {
                    this.filingConnectedDocument = value;
                    this.RaisePropertyChanged("FilingConnectedDocument");
                }
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseType CitationCase
        {
            get
            {
                return (this.caseTypeSelection == CaseTypeSelectionType.CitationCase ? this.filingCase as Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseType : null);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Oasis.LegalXml.CourtFiling.v40.Civil.CivilCaseType CivilCase
        {
            get
            {
                return (this.caseTypeSelection == CaseTypeSelectionType.CivilCase ? this.filingCase as Oasis.LegalXml.CourtFiling.v40.Civil.CivilCaseType : null);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Oasis.LegalXml.CourtFiling.v40.Criminal.CriminalCaseType CriminalCase
        {
            get
            {
                return (this.caseTypeSelection == CaseTypeSelectionType.CriminalCase ? this.filingCase as Oasis.LegalXml.CourtFiling.v40.Criminal.CriminalCaseType : null);
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Oasis.LegalXml.CourtFiling.v40.Domestic.DomesticCaseType DomesticCase
        {
            get
            {
                return (this.caseTypeSelection == CaseTypeSelectionType.DomesticCase ? this.filingCase as Oasis.LegalXml.CourtFiling.v40.Domestic.DomesticCaseType : null);
            }
        }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Oasis.LegalXml.CourtFiling.v40.Juvenile.JuvenileCaseType JuvenileCase
        {
            get
            {
                return (this.caseTypeSelection == CaseTypeSelectionType.JuvenileCase ? this.filingCase as Oasis.LegalXml.CourtFiling.v40.Juvenile.JuvenileCaseType : null);
            }
        }


    }



}
