#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 03:32 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.Proxy.xsd.v20;
using Niem.NiemCore.v20; 

namespace Oasis.LegalXml.CourtFiling.v40.Filing
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:FilingListQueryMessage-4.0", TypeName="FilingListQueryMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("FilingListQueryMessage", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:FilingListQueryMessage-4.0", IsNullable=false, ElementName="FilingListQueryMessageType")]
    
    public partial class FilingListQueryMessageType : QueryMessageType
    {
        
        /// <remarks/>
        private String caseTrackingID;
        
        /// <remarks/>
        private EntityType documentSubmitter;
        
        /// <remarks/>
        private System.Collections.Generic.List<DateRangeType> dateRange;
        
        public FilingListQueryMessageType()
        {
        }
        
        public FilingListQueryMessageType(String caseTrackingID, EntityType documentSubmitter, System.Collections.Generic.List<DateRangeType> dateRange)
        {
            this.caseTrackingID = caseTrackingID;
            this.documentSubmitter = documentSubmitter;
            this.dateRange = dateRange;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true, Order=0, ElementName="CaseTrackingID")]
        public String CaseTrackingID
        {
            get
            {
                return this.caseTrackingID;
            }
            set
            {
                if ((this.caseTrackingID != value))
                {
                    this.caseTrackingID = value;
                    this.RaisePropertyChanged("CaseTrackingID");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true, Order=1, ElementName="DocumentSubmitter")]
        public EntityType DocumentSubmitter
        {
            get
            {
                return this.documentSubmitter;
            }
            set
            {
                if ((this.documentSubmitter != value))
                {
                    this.documentSubmitter = value;
                    this.RaisePropertyChanged("DocumentSubmitter");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("DateRange", Namespace="http://niem.gov/niem/niem-core/2.0", IsNullable=true, Order=2)]
        public System.Collections.Generic.List<DateRangeType> DateRange
        {
            get
            {
                return this.dateRange;
            }
            set
            {
                if ((this.dateRange != value))
                {
                    this.dateRange = value;
                    this.RaisePropertyChanged("DateRange");
                }
            }
        }
    }
    
  
}
