#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 05:20 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf; 

namespace Oasis.LegalXml.CourtFiling.v40.Filing
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ReviewFilingCallbackMessage-4." +
        "0", TypeName="ReviewFilingCallbackMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("ReviewFilingCallbackMessage", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ReviewFilingCallbackMessage-4." +
        "0", IsNullable=false, ElementName="ReviewFilingCallbackMessageType")]
    public partial class ReviewFilingCallbackMessageType : ElectronicFilingCallbackMessageType
    {
        
        public ReviewFilingCallbackMessageType()
        {
        }
    }
    
}
