#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 05:27 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Message;
using Niem.NiemCore.v20; 
namespace Oasis.LegalXml.CourtFiling.v40.Service
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ServiceReceiptMessage-4.0", TypeName="ServiceReceiptMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("ServiceReceiptMessage", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ServiceReceiptMessage-4.0", IsNullable=false, ElementName="ServiceReceiptMessageType")]
    public partial class ServiceReceiptMessageType : MessageReceiptMessageType
    {
        
        /// <remarks/>
        private ServiceRecipientStatusType serviceRecipientStatus;
        
        public ServiceReceiptMessageType()
        {
        }
        
        public ServiceReceiptMessageType(ServiceRecipientStatusType serviceRecipientStatus)
        {
            this.serviceRecipientStatus = serviceRecipientStatus;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="ServiceRecipientStatus")]
        public ServiceRecipientStatusType ServiceRecipientStatus
        {
            get
            {
                return this.serviceRecipientStatus;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ServiceRecipientStatus");
                }
                if ((this.serviceRecipientStatus != value))
                {
                    this.serviceRecipientStatus = value;
                    this.RaisePropertyChanged("ServiceRecipientStatus");
                }
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ServiceReceiptMessage-4.0", TypeName="ServiceRecipientStatusType")]
    [System.Xml.Serialization.XmlRootAttribute("ServiceRecipientStatus", Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:ServiceReceiptMessage-4.0", IsNullable=false, ElementName="ServiceRecipientStatusType")]
    
    public partial class ServiceRecipientStatusType : StatusType
    {
        
        /// <remarks/>
        private IdentificationType serviceRecipientID;
        
        /// <remarks/>
        private string serviceStatusCode;
        
        public ServiceRecipientStatusType()
        {
        }
        
        public ServiceRecipientStatusType(IdentificationType serviceRecipientID, string serviceStatusCode)
        {
            this.serviceRecipientID = serviceRecipientID;
            this.serviceStatusCode = serviceStatusCode;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.0", Order=0, ElementName="ServiceRecipientID")]
        public IdentificationType ServiceRecipientID
        {
            get
            {
                return this.serviceRecipientID;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ServiceRecipientID");
                }
                if ((this.serviceRecipientID != value))
                {
                    this.serviceRecipientID = value;
                    this.RaisePropertyChanged("ServiceRecipientID");
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1, ElementName="ServiceStatusCode")]
        public string ServiceStatusCode
        {
            get
            {
                return this.serviceStatusCode;
            }
            set
            {
                if ((this.serviceStatusCode != value))
                {
                    this.serviceStatusCode = value;
                    this.RaisePropertyChanged("ServiceStatusCode");
                }
            }
        }
    }
    
   }
