/*
	'=======================================================================
	'   Author(s):      D V Rao
	'   Module/Form:    ECF-4.0-FeesCalculationResponseMessage.cs
	'   Created Date:   
	'   Description:    
	'
	'   Modification History:
	'=======================================================================
	'   Author(s)       Date        Control/Procedure       Change
 	'=======================================================================
    '   Rao     04/24/2012       Moved AddNameSpaces to EcfHelper
	'=======================================================================
	*/

#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 03:10 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Oasis.UniversalBusinessLanguage; 

namespace Oasis.LegalXml.CourtFiling.v40.Fees
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:FeesCalculationResponseMessage" +
        "-4.0", TypeName = "FeesCalculationResponseMessageType")]
    [System.Xml.Serialization.XmlRootAttribute("FeesCalculationResponseMessage", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:FeesCalculationResponseMessage" +
        "-4.0", IsNullable = false, ElementName = "FeesCalculationResponseMessageType")]
    
    public partial class FeesCalculationResponseMessageType : QueryResponseMessageType
    {

        /// <remarks/>
        private Niem.NiemCore.v20.AmountType feesCalculationAmount;

        /// <remarks/>
        private System.Collections.Generic.List<AllowanceChargeType> allowanceCharge;

        [field: System.NonSerialized]
        [System.Xml.Serialization.XmlNamespaceDeclarations]
        public System.Xml.Serialization.XmlSerializerNamespaces namespaces = new System.Xml.Serialization.XmlSerializerNamespaces();

        public FeesCalculationResponseMessageType()
        {
            EcfHelper.AddNameSpaces(this.namespaces); 
        }


        public FeesCalculationResponseMessageType(Niem.NiemCore.v20.AmountType feesCalculationAmount, System.Collections.Generic.List<AllowanceChargeType> allowanceCharge)
        {
            EcfHelper.AddNameSpaces(this.namespaces);
            this.feesCalculationAmount = feesCalculationAmount;
            this.allowanceCharge = allowanceCharge;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0, ElementName = "FeesCalculationAmount")]
        public Niem.NiemCore.v20.AmountType FeesCalculationAmount
        {
            get
            {
                return this.feesCalculationAmount;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("FeesCalculationAmount");
                }
                if ((this.feesCalculationAmount != value))
                {
                    this.feesCalculationAmount = value;
                    this.RaisePropertyChanged("FeesCalculationAmount");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("AllowanceCharge", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2", Order = 1)]
        public System.Collections.Generic.List<AllowanceChargeType> AllowanceCharge
        {
            get
            {
                return this.allowanceCharge;
            }
            set
            {
                if ((this.allowanceCharge != value))
                {
                    this.allowanceCharge = value;
                    this.RaisePropertyChanged("AllowanceCharge");
                }
            }
        }
    }

}
