#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 26-11-08 09:15 PM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace Oasis.LegalXml.CourtFiling.v40.AppInfo
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:AppInfo-4.0", TypeName="CodeListReference")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:AppInfo-4.0", IsNullable=false, ElementName="CodeListReference")]
    
    public partial class CodeListReference : object
    {
        
        /// <remarks/>
        private string canonicalURI;
        
        /// <remarks/>
        private string canonicalVersionURI;
        
        /// <remarks/>
        private string locationURI;
        
        public CodeListReference()
        {
        }
        
        public CodeListReference(string canonicalURI, string canonicalVersionURI, string locationURI)
        {
            this.canonicalURI = canonicalURI;
            this.canonicalVersionURI = canonicalVersionURI;
            this.locationURI = locationURI;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="CanonicalURI")]
        public string CanonicalURI
        {
            get
            {
                return this.canonicalURI;
            }
            set
            {
                if ((this.canonicalURI != value))
                {
                    this.canonicalURI = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="CanonicalVersionURI")]
        public string CanonicalVersionURI
        {
            get
            {
                return this.canonicalVersionURI;
            }
            set
            {
                if ((this.canonicalVersionURI != value))
                {
                    this.canonicalVersionURI = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="anyURI", AttributeName="LocationURI")]
        public string LocationURI
        {
            get
            {
                return this.locationURI;
            }
            set
            {
                if ((this.locationURI != value))
                {
                    this.locationURI = value;
                }
            }
        }
        
    }
}
