#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 27-11-08 09:13 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion


namespace W3.DigitalSignature
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureType")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignatureType")]
    
    public partial class SignatureType : object 
    {
        
        /// <remarks/>
        private SignedInfoType signedInfo;
        
        /// <remarks/>
        private SignatureValueType signatureValue;
        
        /// <remarks/>
        private KeyInfoType keyInfo;
        
        /// <remarks/>
        private System.Collections.Generic.List<ObjectType> @object;
        
        /// <remarks/>
        private string id;
        
        public SignatureType()
        {
        }
        
        public SignatureType(SignedInfoType signedInfo, SignatureValueType signatureValue, KeyInfoType keyInfo, System.Collections.Generic.List<ObjectType> @object, string id)
        {
            this.signedInfo = signedInfo;
            this.signatureValue = signatureValue;
            this.keyInfo = keyInfo;
            this.@object = @object;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="SignedInfo")]
        public SignedInfoType SignedInfo
        {
            get
            {
                return this.signedInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SignedInfo");
                }
                if ((this.signedInfo != value))
                {
                    this.signedInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="SignatureValue")]
        public SignatureValueType SignatureValue
        {
            get
            {
                return this.signatureValue;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SignatureValue");
                }
                if ((this.signatureValue != value))
                {
                    this.signatureValue = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2, ElementName="KeyInfo")]
        public KeyInfoType KeyInfo
        {
            get
            {
                return this.keyInfo;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("KeyInfo");
                }
                if ((this.keyInfo != value))
                {
                    this.keyInfo = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Object", Order=3)]
        public System.Collections.Generic.List<ObjectType> Object
        {
            get
            {
                return this.@object;
            }
            set
            {
                if ((this.@object != value))
                {
                    this.@object = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignedInfoType")]
    [System.Xml.Serialization.XmlRootAttribute("SignedInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignedInfoType")]
    
    public partial class SignedInfoType : object 
    {
        
        /// <remarks/>
        private CanonicalizationMethodType canonicalizationMethod;
        
        /// <remarks/>
        private SignatureMethodType signatureMethod;
        
        /// <remarks/>
        private System.Collections.Generic.List<ReferenceType> reference;
        
        /// <remarks/>
        private string id;
        
        public SignedInfoType()
        {
        }
        
        public SignedInfoType(CanonicalizationMethodType canonicalizationMethod, SignatureMethodType signatureMethod, System.Collections.Generic.List<ReferenceType> reference, string id)
        {
            this.canonicalizationMethod = canonicalizationMethod;
            this.signatureMethod = signatureMethod;
            this.reference = reference;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="CanonicalizationMethod")]
        public CanonicalizationMethodType CanonicalizationMethod
        {
            get
            {
                return this.canonicalizationMethod;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CanonicalizationMethod");
                }
                if ((this.canonicalizationMethod != value))
                {
                    this.canonicalizationMethod = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="SignatureMethod")]
        public SignatureMethodType SignatureMethod
        {
            get
            {
                return this.signatureMethod;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("SignatureMethod");
                }
                if ((this.signatureMethod != value))
                {
                    this.signatureMethod = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=2)]
        public System.Collections.Generic.List<ReferenceType> Reference
        {
            get
            {
                return this.reference;
            }
            set
            {
                if ((this.reference != value))
                {
                    this.reference = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="CanonicalizationMethodType")]
    [System.Xml.Serialization.XmlRootAttribute("CanonicalizationMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="CanonicalizationMethodType")]
    
    public partial class CanonicalizationMethodType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlNode> any;
        
        /// <remarks/>
        private string algorithm;
        
        public CanonicalizationMethodType()
        {
        }
        
        public CanonicalizationMethodType(System.Collections.Generic.List<System.Xml.XmlNode> any, string algorithm)
        {
            this.any = any;
            this.algorithm = algorithm;
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Collections.Generic.List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.any;
            }
            set
            {
                if ((this.any != value))
                {
                    this.any = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm
        {
            get
            {
                return this.algorithm;
            }
            set
            {
                if ((this.algorithm != value))
                {
                    this.algorithm = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ObjectType")]
    [System.Xml.Serialization.XmlRootAttribute("Object", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="ObjectType")]
    
    public partial class ObjectType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlNode> any;
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string mimeType;
        
        /// <remarks/>
        private string encoding;
        
        public ObjectType()
        {
        }
        
        public ObjectType(System.Collections.Generic.List<System.Xml.XmlNode> any, string id, string mimeType, string encoding)
        {
            this.any = any;
            this.id = id;
            this.mimeType = mimeType;
            this.encoding = encoding;
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Collections.Generic.List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.any;
            }
            set
            {
                if ((this.any != value))
                {
                    this.any = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="MimeType")]
        public string MimeType
        {
            get
            {
                return this.mimeType;
            }
            set
            {
                if ((this.mimeType != value))
                {
                    this.mimeType = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Encoding")]
        public string Encoding
        {
            get
            {
                return this.encoding;
            }
            set
            {
                if ((this.encoding != value))
                {
                    this.encoding = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SPKIDataType")]
    [System.Xml.Serialization.XmlRootAttribute("SPKIData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SPKIDataType")]
    
    public partial class SPKIDataType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<object> items;
        
        public SPKIDataType()
        {
        }
        
        public SPKIDataType(System.Collections.Generic.List<object> items)
        {
            this.items = items;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", typeof(byte[]), DataType="base64Binary", Order=0)]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="PGPDataType")]
    [System.Xml.Serialization.XmlRootAttribute("PGPData", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="PGPDataType")]
    
    public partial class PGPDataType : object 
    {
        
        /// <remarks/>
        private object[] items;
        
        /// <remarks/>
        private ItemsChoiceType1[] itemsElementName;
        
        public PGPDataType()
        {
        }
        
        public PGPDataType(object[] items, ItemsChoiceType1[] itemsElementName)
        {
            this.items = items;
            this.itemsElementName = itemsElementName;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementName;
            }
            set
            {
                if ((this.itemsElementName != value))
                {
                    this.itemsElementName = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false, TypeName="ItemsChoiceType1")]
    public enum ItemsChoiceType1
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PGPKeyID")]
        PGPKeyID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PGPKeyPacket")]
        PGPKeyPacket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="X509IssuerSerialType")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=true, ElementName="X509IssuerSerialType")]
    
    public partial class X509IssuerSerialType : object 
    {
        
        /// <remarks/>
        private string x509IssuerName;
        
        /// <remarks/>
        private string x509SerialNumber;
        
        public X509IssuerSerialType()
        {
        }
        
        public X509IssuerSerialType(string x509IssuerName, string x509SerialNumber)
        {
            this.x509IssuerName = x509IssuerName;
            this.x509SerialNumber = x509SerialNumber;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0, ElementName="X509IssuerName")]
        public string X509IssuerName
        {
            get
            {
                return this.x509IssuerName;
            }
            set
            {
                if ((this.x509IssuerName != value))
                {
                    this.x509IssuerName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1, ElementName="X509SerialNumber")]
        public string X509SerialNumber
        {
            get
            {
                return this.x509SerialNumber;
            }
            set
            {
                if ((this.x509SerialNumber != value))
                {
                    this.x509SerialNumber = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="X509DataType")]
    [System.Xml.Serialization.XmlRootAttribute("X509Data", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="X509DataType")]
    
    public partial class X509DataType : object 
    {
        
        /// <remarks/>
        private object[] items;
        
        /// <remarks/>
        private ItemsChoiceType[] itemsElementName;
        
        public X509DataType()
        {
        }
        
        public X509DataType(object[] items, ItemsChoiceType[] itemsElementName)
        {
            this.items = items;
            this.itemsElementName = itemsElementName;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementName;
            }
            set
            {
                if ((this.itemsElementName != value))
                {
                    this.itemsElementName = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false, TypeName="ItemsChoiceType")]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509CRL")]
        X509CRL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509Certificate")]
        X509Certificate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509IssuerSerial")]
        X509IssuerSerial,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509SKI")]
        X509SKI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509SubjectName")]
        X509SubjectName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="RetrievalMethodType")]
    [System.Xml.Serialization.XmlRootAttribute("RetrievalMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="RetrievalMethodType")]
    
    public partial class RetrievalMethodType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<TransformType> transforms;
        
        /// <remarks/>
        private string uRI;
        
        /// <remarks/>
        private string type;
        
        public RetrievalMethodType()
        {
        }
        
        public RetrievalMethodType(System.Collections.Generic.List<TransformType> transforms, string uRI, string type)
        {
            this.transforms = transforms;
            this.uRI = uRI;
            this.type = type;
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0, ElementName="Transforms")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public System.Collections.Generic.List<TransformType> Transforms
        {
            get
            {
                return this.transforms;
            }
            set
            {
                if ((this.transforms != value))
                {
                    this.transforms = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="URI")]
        public string URI
        {
            get
            {
                return this.uRI;
            }
            set
            {
                if ((this.uRI != value))
                {
                    this.uRI = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Type")]
        public string Type
        {
            get
            {
                return this.type;
            }
            set
            {
                if ((this.type != value))
                {
                    this.type = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="TransformType")]
    [System.Xml.Serialization.XmlRootAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="TransformType")]
    
    public partial class TransformType : object 
    {
        
        /// <remarks/>
        private object[] items;
        
        /// <remarks/>
        private System.Collections.Generic.List<string> text;
        
        /// <remarks/>
        private string algorithm;
        
        public TransformType()
        {
        }
        
        public TransformType(object[] items, System.Collections.Generic.List<string> text, string algorithm)
        {
            this.items = items;
            this.text = text;
            this.algorithm = algorithm;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string), Order=0)]
        public object[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Collections.Generic.List<string> Text
        {
            get
            {
                return this.text;
            }
            set
            {
                if ((this.text != value))
                {
                    this.text = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm
        {
            get
            {
                return this.algorithm;
            }
            set
            {
                if ((this.algorithm != value))
                {
                    this.algorithm = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="RSAKeyValueType")]
    [System.Xml.Serialization.XmlRootAttribute("RSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="RSAKeyValueType")]
    
    public partial class RSAKeyValueType : object 
    {
        
        /// <remarks/>
        private byte[] modulus;
        
        /// <remarks/>
        private byte[] exponent;
        
        public RSAKeyValueType()
        {
        }
        
        public RSAKeyValueType(byte[] modulus, byte[] exponent)
        {
            this.modulus = modulus;
            this.exponent = exponent;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0, ElementName="Modulus")]
        public byte[] Modulus
        {
            get
            {
                return this.modulus;
            }
            set
            {
                if ((this.modulus != value))
                {
                    this.modulus = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1, ElementName="Exponent")]
        public byte[] Exponent
        {
            get
            {
                return this.exponent;
            }
            set
            {
                if ((this.exponent != value))
                {
                    this.exponent = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="DSAKeyValueType")]
    [System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="DSAKeyValueType")]
    
    public partial class DSAKeyValueType : object 
    {
        
        /// <remarks/>
        private byte[] p;
        
        /// <remarks/>
        private byte[] q;
        
        /// <remarks/>
        private byte[] g;
        
        /// <remarks/>
        private byte[] y;
        
        /// <remarks/>
        private byte[] j;
        
        /// <remarks/>
        private byte[] seed;
        
        /// <remarks/>
        private byte[] pgenCounter;
        
        public DSAKeyValueType()
        {
        }
        
        public DSAKeyValueType(byte[] p, byte[] q, byte[] g, byte[] y, byte[] j, byte[] seed, byte[] pgenCounter)
        {
            this.p = p;
            this.q = q;
            this.g = g;
            this.y = y;
            this.j = j;
            this.seed = seed;
            this.pgenCounter = pgenCounter;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0, ElementName="P")]
        public byte[] P
        {
            get
            {
                return this.p;
            }
            set
            {
                if ((this.p != value))
                {
                    this.p = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1, ElementName="Q")]
        public byte[] Q
        {
            get
            {
                return this.q;
            }
            set
            {
                if ((this.q != value))
                {
                    this.q = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2, ElementName="G")]
        public byte[] G
        {
            get
            {
                return this.g;
            }
            set
            {
                if ((this.g != value))
                {
                    this.g = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3, ElementName="Y")]
        public byte[] Y
        {
            get
            {
                return this.y;
            }
            set
            {
                if ((this.y != value))
                {
                    this.y = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4, ElementName="J")]
        public byte[] J
        {
            get
            {
                return this.j;
            }
            set
            {
                if ((this.j != value))
                {
                    this.j = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5, ElementName="Seed")]
        public byte[] Seed
        {
            get
            {
                return this.seed;
            }
            set
            {
                if ((this.seed != value))
                {
                    this.seed = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6, ElementName="PgenCounter")]
        public byte[] PgenCounter
        {
            get
            {
                return this.pgenCounter;
            }
            set
            {
                if ((this.pgenCounter != value))
                {
                    this.pgenCounter = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="KeyValueType")]
    [System.Xml.Serialization.XmlRootAttribute("KeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="KeyValueType")]
    
    public partial class KeyValueType : object 
    {
        
        /// <remarks/>
        private object item;
        
        /// <remarks/>
        private System.Collections.Generic.List<string> text;
        
        public KeyValueType()
        {
        }
        
        public KeyValueType(object item, System.Collections.Generic.List<string> text)
        {
            this.item = item;
            this.text = text;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType), Order=0)]
        public object Item
        {
            get
            {
                return this.item;
            }
            set
            {
                if ((this.item != value))
                {
                    this.item = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Collections.Generic.List<string> Text
        {
            get
            {
                return this.text;
            }
            set
            {
                if ((this.text != value))
                {
                    this.text = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="KeyInfoType")]
    [System.Xml.Serialization.XmlRootAttribute("KeyInfo", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="KeyInfoType")]
    
    public partial class KeyInfoType : object 
    {
        
        /// <remarks/>
        private object[] items;
        
        /// <remarks/>
        private ItemsChoiceType2[] itemsElementName;
        
        /// <remarks/>
        private System.Collections.Generic.List<string> text;
        
        /// <remarks/>
        private string id;
        
        public KeyInfoType()
        {
        }
        
        public KeyInfoType(object[] items, ItemsChoiceType2[] itemsElementName, System.Collections.Generic.List<string> text, string id)
        {
            this.items = items;
            this.itemsElementName = itemsElementName;
            this.text = text;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return this.itemsElementName;
            }
            set
            {
                if ((this.itemsElementName != value))
                {
                    this.itemsElementName = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Collections.Generic.List<string> Text
        {
            get
            {
                return this.text;
            }
            set
            {
                if ((this.text != value))
                {
                    this.text = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false, TypeName="ItemsChoiceType2")]
    public enum ItemsChoiceType2
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KeyName")]
        KeyName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KeyValue")]
        KeyValue,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MgmtData")]
        MgmtData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PGPData")]
        PGPData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RetrievalMethod")]
        RetrievalMethod,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SPKIData")]
        SPKIData,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509Data")]
        X509Data,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureValueType")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureValue", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignatureValueType")]
    
    public partial class SignatureValueType : object 
    {
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private byte[] value;
        
        public SignatureValueType()
        {
        }
        
        public SignatureValueType(string id, byte[] value)
        {
            this.id = id;
            this.value = value;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.value;
            }
            set
            {
                if ((this.value != value))
                {
                    this.value = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="DigestMethodType")]
    [System.Xml.Serialization.XmlRootAttribute("DigestMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="DigestMethodType")]
    
    public partial class DigestMethodType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlNode> any;
        
        /// <remarks/>
        private string algorithm;
        
        public DigestMethodType()
        {
        }
        
        public DigestMethodType(System.Collections.Generic.List<System.Xml.XmlNode> any, string algorithm)
        {
            this.any = any;
            this.algorithm = algorithm;
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Collections.Generic.List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.any;
            }
            set
            {
                if ((this.any != value))
                {
                    this.any = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm
        {
            get
            {
                return this.algorithm;
            }
            set
            {
                if ((this.algorithm != value))
                {
                    this.algorithm = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ReferenceType")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="ReferenceType")]
    
    public partial class ReferenceType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<TransformType> transforms;
        
        /// <remarks/>
        private DigestMethodType digestMethod;
        
        /// <remarks/>
        private byte[] digestValue;
        
        /// <remarks/>
        private string id;
        
        /// <remarks/>
        private string uRI;
        
        /// <remarks/>
        private string type;
        
        public ReferenceType()
        {
        }
        
        public ReferenceType(System.Collections.Generic.List<TransformType> transforms, DigestMethodType digestMethod, byte[] digestValue, string id, string uRI, string type)
        {
            this.transforms = transforms;
            this.digestMethod = digestMethod;
            this.digestValue = digestValue;
            this.id = id;
            this.uRI = uRI;
            this.type = type;
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=0, ElementName="Transforms")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public System.Collections.Generic.List<TransformType> Transforms
        {
            get
            {
                return this.transforms;
            }
            set
            {
                if ((this.transforms != value))
                {
                    this.transforms = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1, ElementName="DigestMethod")]
        public DigestMethodType DigestMethod
        {
            get
            {
                return this.digestMethod;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("DigestMethod");
                }
                if ((this.digestMethod != value))
                {
                    this.digestMethod = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2, ElementName="DigestValue")]
        public byte[] DigestValue
        {
            get
            {
                return this.digestValue;
            }
            set
            {
                if ((this.digestValue != value))
                {
                    this.digestValue = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="URI")]
        public string URI
        {
            get
            {
                return this.uRI;
            }
            set
            {
                if ((this.uRI != value))
                {
                    this.uRI = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Type")]
        public string Type
        {
            get
            {
                return this.type;
            }
            set
            {
                if ((this.type != value))
                {
                    this.type = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureMethodType")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureMethod", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignatureMethodType")]
    
    public partial class SignatureMethodType : object 
    {
        
        /// <remarks/>
        private string hMACOutputLength;
        
        /// <remarks/>
        private System.Collections.Generic.List<System.Xml.XmlNode> any;
        
        /// <remarks/>
        private string algorithm;
        
        public SignatureMethodType()
        {
        }
        
        public SignatureMethodType(string hMACOutputLength, System.Collections.Generic.List<System.Xml.XmlNode> any, string algorithm)
        {
            this.hMACOutputLength = hMACOutputLength;
            this.any = any;
            this.algorithm = algorithm;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0, ElementName="HMACOutputLength")]
        public string HMACOutputLength
        {
            get
            {
                return this.hMACOutputLength;
            }
            set
            {
                if ((this.hMACOutputLength != value))
                {
                    this.hMACOutputLength = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Collections.Generic.List<System.Xml.XmlNode> Any
        {
            get
            {
                return this.any;
            }
            set
            {
                if ((this.any != value))
                {
                    this.any = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm
        {
            get
            {
                return this.algorithm;
            }
            set
            {
                if ((this.algorithm != value))
                {
                    this.algorithm = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="TransformsType")]
    [System.Xml.Serialization.XmlRootAttribute("Transforms", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="TransformsType")]
    
    public partial class TransformsType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<TransformType> transform;
        
        public TransformsType()
        {
        }
        
        public TransformsType(System.Collections.Generic.List<TransformType> transform)
        {
            this.transform = transform;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Transform", Order=0)]
        public System.Collections.Generic.List<TransformType> Transform
        {
            get
            {
                return this.transform;
            }
            set
            {
                if ((this.transform != value))
                {
                    this.transform = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ManifestType")]
    [System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="ManifestType")]
    
    public partial class ManifestType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<ReferenceType> reference;
        
        /// <remarks/>
        private string id;
        
        public ManifestType()
        {
        }
        
        public ManifestType(System.Collections.Generic.List<ReferenceType> reference, string id)
        {
            this.reference = reference;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=0)]
        public System.Collections.Generic.List<ReferenceType> Reference
        {
            get
            {
                return this.reference;
            }
            set
            {
                if ((this.reference != value))
                {
                    this.reference = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignaturePropertiesType")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperties", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignaturePropertiesType")]
    
    public partial class SignaturePropertiesType : object 
    {
        
        /// <remarks/>
        private System.Collections.Generic.List<SignaturePropertyType> signatureProperty;
        
        /// <remarks/>
        private string id;
        
        public SignaturePropertiesType()
        {
        }
        
        public SignaturePropertiesType(System.Collections.Generic.List<SignaturePropertyType> signatureProperty, string id)
        {
            this.signatureProperty = signatureProperty;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SignatureProperty", Order=0)]
        public System.Collections.Generic.List<SignaturePropertyType> SignatureProperty
        {
            get
            {
                return this.signatureProperty;
            }
            set
            {
                if ((this.signatureProperty != value))
                {
                    this.signatureProperty = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignaturePropertyType")]
    [System.Xml.Serialization.XmlRootAttribute("SignatureProperty", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false, ElementName="SignaturePropertyType")]
    
    public partial class SignaturePropertyType : object 
    {
        
        /// <remarks/>
        private System.Xml.XmlElement[] items;
        
        /// <remarks/>
        private System.Collections.Generic.List<string> text;
        
        /// <remarks/>
        private string target;
        
        /// <remarks/>
        private string id;
        
        public SignaturePropertyType()
        {
        }
        
        public SignaturePropertyType(System.Xml.XmlElement[] items, System.Collections.Generic.List<string> text, string target, string id)
        {
            this.items = items;
            this.text = text;
            this.target = target;
            this.id = id;
        }
        
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.items;
            }
            set
            {
                if ((this.items != value))
                {
                    this.items = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Collections.Generic.List<string> Text
        {
            get
            {
                return this.text;
            }
            set
            {
                if ((this.text != value))
                {
                    this.text = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Target")]
        public string Target
        {
            get
            {
                return this.target;
            }
            set
            {
                if ((this.target != value))
                {
                    this.target = value;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id
        {
            get
            {
                return this.id;
            }
            set
            {
                if ((this.id != value))
                {
                    this.id = value;
                }
            }
        }
        
    }
}
