#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 12-01-10 10:39 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.NiemCore.v20;
using Niem.Proxy.xsd.v20;
using Niem.Structures.v20;
using Niem.Domains.Jxdm.v40;

namespace Oasis.LegalXml.CourtFiling.v40.Criminal
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", TypeName = "CriminalCaseType")]
    [System.Xml.Serialization.XmlRootAttribute("CriminalCase", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = false, ElementName = "CriminalCase")]
    public partial class CriminalCaseType : CaseType
    {
        private Niem.Domains.Jxdm.v40.CaseAugmentationType caseAugmentation;
        private Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType ecfCaseAugmentation;
        private Niem.Domains.Jxdm.v40.ArrestType caseArrest;
        private System.Collections.Generic.List<ChargeType> caseCharge;
        private Duration preliminaryHearingEstimatedDuration;
        private TextType prosecutionRecommendedBailText;
        private System.Collections.Generic.List<SentenceType> sentence;
        private Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseAugmentationType citationCaseAugmentation;

        public CriminalCaseType()
        {
        }

        public CriminalCaseType(Niem.Domains.Jxdm.v40.CaseAugmentationType caseAugmentation, Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType ecfCaseAugmentation, Niem.Domains.Jxdm.v40.ArrestType caseArrest, System.Collections.Generic.List<ChargeType> caseCharge, Duration preliminaryHearingEstimatedDuration, TextType prosecutionRecommendedBailText, System.Collections.Generic.List<SentenceType> sentence, Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseAugmentationType citationCaseAugmentation)
        {
            this.caseAugmentation = caseAugmentation;
            this.ecfCaseAugmentation = ecfCaseAugmentation;
            this.caseArrest = caseArrest;
            this.caseCharge = caseCharge;
            this.preliminaryHearingEstimatedDuration = preliminaryHearingEstimatedDuration;
            this.prosecutionRecommendedBailText = prosecutionRecommendedBailText;
            this.sentence = sentence;
            this.citationCaseAugmentation = citationCaseAugmentation;
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/domains/jxdm/4.0", Order = 0, ElementName = "CaseAugmentation")]
        public Niem.Domains.Jxdm.v40.CaseAugmentationType CaseAugmentation
        {
            get
            {
                return this.caseAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CaseAugmentation");
                }
                if ((this.caseAugmentation != value))
                {
                    this.caseAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseAugmentation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.0", Order = 1)]
        public Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType EcfCaseAugmentation
        {
            get
            {
                return this.ecfCaseAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("EcfCaseAugmentation");
                }
                if ((this.ecfCaseAugmentation != value))
                {
                    this.ecfCaseAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "CaseArrest")]
        public Niem.Domains.Jxdm.v40.ArrestType CaseArrest
        {
            get
            {
                return this.caseArrest;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CaseArrest");
                }
                if ((this.caseArrest != value))
                {
                    this.caseArrest = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseCharge", Order = 3)]
        public System.Collections.Generic.List<ChargeType> CaseCharge
        {
            get
            {
                return this.caseCharge;
            }
            set
            {
                if ((this.caseCharge != value))
                {
                    this.caseCharge = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4, ElementName = "PreliminaryHearingEstimatedDuration")]
        public Duration PreliminaryHearingEstimatedDuration
        {
            get
            {
                return this.preliminaryHearingEstimatedDuration;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("PreliminaryHearingEstimatedDuration");
                }
                if ((this.preliminaryHearingEstimatedDuration != value))
                {
                    this.preliminaryHearingEstimatedDuration = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5, ElementName = "ProsecutionRecommendedBailText")]
        public TextType ProsecutionRecommendedBailText
        {
            get
            {
                return this.prosecutionRecommendedBailText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ProsecutionRecommendedBailText");
                }
                if ((this.prosecutionRecommendedBailText != value))
                {
                    this.prosecutionRecommendedBailText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Sentence", Order = 6)]
        public System.Collections.Generic.List<SentenceType> Sentence
        {
            get
            {
                return this.sentence;
            }
            set
            {
                if ((this.sentence != value))
                {
                    this.sentence = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CitationCase-4.0", Order = 7, ElementName = "CitationCaseAugmentation")]
        public Oasis.LegalXml.CourtFiling.v40.Citation.CitationCaseAugmentationType CitationCaseAugmentation
        {
            get
            {
                return this.citationCaseAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CitationCaseAugmentation");
                }
                if ((this.citationCaseAugmentation != value))
                {
                    this.citationCaseAugmentation = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ChargeType", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0")]
    [System.Xml.Serialization.XmlRootAttribute("CaseCharge", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = false, ElementName = "ChargeType")]
    public partial class ChargeType : Niem.Domains.Jxdm.v40.ChargeType
    {

        private Niem.NiemCore.v20.IncidentType chargeOffense;
        private System.Collections.Generic.List<Niem.Domains.Jxdm.v40.StatuteType> chargeChargingAgencyJurisdictionStatute;
        private Boolean chargeAmendedIndicator;

        public ChargeType()
        {
        }

        public ChargeType(Niem.NiemCore.v20.IncidentType chargeOffense, System.Collections.Generic.List<Niem.Domains.Jxdm.v40.StatuteType> chargeChargingAgencyJurisdictionStatute, Boolean chargeAmendedIndicator)
        {
            this.chargeOffense = chargeOffense;
            this.chargeChargingAgencyJurisdictionStatute = chargeChargingAgencyJurisdictionStatute;
            this.chargeAmendedIndicator = chargeAmendedIndicator;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0, ElementName = "ChargeOffense")]
        public Niem.NiemCore.v20.IncidentType ChargeOffense
        {
            get
            {
                return this.chargeOffense;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ChargeOffense");
                }
                if ((this.chargeOffense != value))
                {
                    this.chargeOffense = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ChargeChargingAgencyJurisdictionStatute", Order = 1)]
        public System.Collections.Generic.List<Niem.Domains.Jxdm.v40.StatuteType> ChargeChargingAgencyJurisdictionStatute
        {
            get
            {
                return this.chargeChargingAgencyJurisdictionStatute;
            }
            set
            {
                if ((this.chargeChargingAgencyJurisdictionStatute != value))
                {
                    this.chargeChargingAgencyJurisdictionStatute = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "ChargeAmendedIndicator")]
        public Boolean ChargeAmendedIndicator
        {
            get
            {
                return this.chargeAmendedIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ChargeAmendedIndicator");
                }
                if ((this.chargeAmendedIndicator != value))
                {
                    this.chargeAmendedIndicator = value;
                }
            }
        }
    }


    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "FingerprintType", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0")]
    [System.Xml.Serialization.XmlRootAttribute("Fingerprint", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = false, ElementName = "Fingerprint")]
    public partial class FingerprintType : Niem.AnsiNist.v20.FingerprintType
    {
        private System.Collections.Generic.List<Niem.NiemCore.v20.ImageType> fingerprintImage;

        public FingerprintType()
        {
        }

        public FingerprintType(System.Collections.Generic.List<Niem.NiemCore.v20.ImageType> fingerprintImage)
        {
            this.fingerprintImage = fingerprintImage;
        }

        [System.Xml.Serialization.XmlElementAttribute("FingerprintImage", Order = 0)]
        public System.Collections.Generic.List<Niem.NiemCore.v20.ImageType> FingerprintImage
        {
            get
            {
                return this.fingerprintImage;
            }
            set
            {
                if ((this.fingerprintImage != value))
                {
                    this.fingerprintImage = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SentenceType", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0")]
    [System.Xml.Serialization.XmlRootAttribute("Sentence", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = false, ElementName = "Sentence")]
    public partial class SentenceType : Niem.Domains.Jxdm.v40.SentenceType
    {

        private System.Collections.Generic.List<Niem.NiemCore.v20.RelatedActivityAssociationType> sentenceConcurrentAssociation;
        private System.Collections.Generic.List<AmountType> sentenceFineAmount;
        private System.Collections.Generic.List<ReferenceType> chargeReference;

        public SentenceType()
        {
        }

        public SentenceType(System.Collections.Generic.List<Niem.NiemCore.v20.RelatedActivityAssociationType> sentenceConcurrentAssociation, System.Collections.Generic.List<AmountType> sentenceFineAmount, System.Collections.Generic.List<ReferenceType> chargeReference)
        {
            this.sentenceConcurrentAssociation = sentenceConcurrentAssociation;
            this.sentenceFineAmount = sentenceFineAmount;
            this.chargeReference = chargeReference;
        }

        [System.Xml.Serialization.XmlElementAttribute("SentenceConcurrentAssociation", Order = 0)]
        public System.Collections.Generic.List<Niem.NiemCore.v20.RelatedActivityAssociationType> SentenceConcurrentAssociation
        {
            get
            {
                return this.sentenceConcurrentAssociation;
            }
            set
            {
                if ((this.sentenceConcurrentAssociation != value))
                {
                    this.sentenceConcurrentAssociation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("SentenceFineAmount", Order = 1)]
        public System.Collections.Generic.List<AmountType> SentenceFineAmount
        {
            get
            {
                return this.sentenceFineAmount;
            }
            set
            {
                if ((this.sentenceFineAmount != value))
                {
                    this.sentenceFineAmount = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ChargeReference", Namespace = "http://niem.gov/niem/domains/jxdm/4.0", Order = 2)]
        public System.Collections.Generic.List<ReferenceType> ChargeReference
        {
            get
            {
                return this.chargeReference;
            }
            set
            {
                if ((this.chargeReference != value))
                {
                    this.chargeReference = value;
                }
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SubjectType", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0")]
    [System.Xml.Serialization.XmlRootAttribute("Subject", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CriminalCase-4.0", IsNullable = false, ElementName = "SubjectType")]
    [System.ComponentModel.TypeConverterAttribute(typeof(System.ComponentModel.ExpandableObjectConverter))]
    public partial class SubjectType : Niem.Domains.Jxdm.v40.SubjectType
    {
        private Niem.Domains.Jxdm.v40.PersonAugmentationType personAugmentation;
        private Oasis.LegalXml.CourtFiling.v40.Ecf.PersonAugmentationType ecfPersonAugmentation;
        private Boolean personInCustodyIndicator;
        private Boolean warrantIssuedIndicator;

        public SubjectType()
        {
        }

        public SubjectType(Niem.Domains.Jxdm.v40.PersonAugmentationType personAugmentation, Oasis.LegalXml.CourtFiling.v40.Ecf.PersonAugmentationType ecfPersonAugmentation, Boolean personInCustodyIndicator, Boolean warrantIssuedIndicator)
        {
            this.personAugmentation = personAugmentation;
            this.ecfPersonAugmentation = ecfPersonAugmentation;
            this.personInCustodyIndicator = personInCustodyIndicator;
            this.warrantIssuedIndicator = warrantIssuedIndicator;
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/domains/jxdm/4.0", Order = 0, ElementName = "PersonAugmentation")]
        public Niem.Domains.Jxdm.v40.PersonAugmentationType PersonAugmentation
        {
            get
            {
                return this.personAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("PersonAugmentation");
                }
                if ((this.personAugmentation != value))
                {
                    this.personAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("PersonAugmentation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.0", Order = 1)]
        public Oasis.LegalXml.CourtFiling.v40.Ecf.PersonAugmentationType EcfPersonAugmentation
        {
            get
            {
                return this.ecfPersonAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("EcfPersonAugmentation");
                }
                if ((this.ecfPersonAugmentation != value))
                {
                    this.ecfPersonAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "PersonInCustodyIndicator")]
        public Boolean PersonInCustodyIndicator
        {
            get
            {
                return this.personInCustodyIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("PersonInCustodyIndicator");
                }
                if ((this.personInCustodyIndicator != value))
                {
                    this.personInCustodyIndicator = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3, ElementName = "WarrantIssuedIndicator")]
        public Boolean WarrantIssuedIndicator
        {
            get
            {
                return this.warrantIssuedIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("WarrantIssuedIndicator");
                }
                if ((this.warrantIssuedIndicator != value))
                {
                    this.warrantIssuedIndicator = value;
                }
            }
        }
    }

}
