#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 12-01-10 11:36 AM
//
// This source code was auto-generated by WsContractFirst, Version=0.7.6319.1
#endregion

using Oasis.LegalXml.CourtFiling.v40.Ecf;
using Niem.NiemCore.v20;
using Niem.Proxy.xsd.v20;
using Niem.Structures.v20;
using Niem.Domains.Jxdm.v40;

namespace Oasis.LegalXml.CourtFiling.v40.Domestic
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "DomesticCaseType")]
    [System.Xml.Serialization.XmlRootAttribute("DomesticCase", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "DomesticCaseType")]
    public partial class DomesticCaseType : CaseType
    {

        private Niem.Domains.Jxdm.v40.CaseAugmentationType caseAugmentation;
        private Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType ecfCaseAugmentation;
        private System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> immediateFamilyAssociation;
        private TextType causeOfActionCode;
        private Boolean caseContestedIndicator;
        private System.Collections.Generic.List<Oasis.LegalXml.CourtFiling.v40.Ecf.PersonType> domesticCasePerson;
        private DomesticCaseViolencePetitionType domesticCaseViolencePetition;
        private System.Collections.Generic.List<DomesticCaseChildSupportPetitionType> domesticCaseChildSupportPetition;
        private System.Collections.Generic.List<DomesticCaseOrderType> domesticCaseOrder;
        private System.Collections.Generic.List<MarriageAssociationType> marriageAssociation;

        public DomesticCaseType()
        {
        }

        public DomesticCaseType(Niem.Domains.Jxdm.v40.CaseAugmentationType caseAugmentation, Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType ecfCaseAugmentation, System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> immediateFamilyAssociation, TextType causeOfActionCode, Boolean caseContestedIndicator, System.Collections.Generic.List<Oasis.LegalXml.CourtFiling.v40.Ecf.PersonType> domesticCasePerson, DomesticCaseViolencePetitionType domesticCaseViolencePetition, System.Collections.Generic.List<DomesticCaseChildSupportPetitionType> domesticCaseChildSupportPetition, System.Collections.Generic.List<DomesticCaseOrderType> domesticCaseOrder, System.Collections.Generic.List<MarriageAssociationType> marriageAssociation)
        {
            this.caseAugmentation = caseAugmentation;
            this.ecfCaseAugmentation = ecfCaseAugmentation;
            this.immediateFamilyAssociation = immediateFamilyAssociation;
            this.causeOfActionCode = causeOfActionCode;
            this.caseContestedIndicator = caseContestedIndicator;
            this.domesticCasePerson = domesticCasePerson;
            this.domesticCaseViolencePetition = domesticCaseViolencePetition;
            this.domesticCaseChildSupportPetition = domesticCaseChildSupportPetition;
            this.domesticCaseOrder = domesticCaseOrder;
            this.marriageAssociation = marriageAssociation;
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/domains/jxdm/4.0", Order = 0, ElementName = "CaseAugmentation")]
        public Niem.Domains.Jxdm.v40.CaseAugmentationType CaseAugmentation
        {
            get
            {
                return this.caseAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CaseAugmentation");
                }
                if ((this.caseAugmentation != value))
                {
                    this.caseAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("CaseAugmentation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.0", Order = 1)]
        public Oasis.LegalXml.CourtFiling.v40.Ecf.CaseAugmentationType EcfCaseAugmentation 
        {
            get
            {
                return this.ecfCaseAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("EcfCaseAugmentation");
                }
                if ((this.ecfCaseAugmentation != value))
                {
                    this.ecfCaseAugmentation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ImmediateFamilyAssociation", Namespace = "http://niem.gov/niem/niem-core/2.0", IsNullable = true, Order = 2)]
        public System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> ImmediateFamilyAssociation
        {
            get
            {
                return this.immediateFamilyAssociation;
            }
            set
            {
                if ((this.immediateFamilyAssociation != value))
                {
                    this.immediateFamilyAssociation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:CommonTypes-4.0", Order = 3, ElementName = "CauseOfActionCode")]
        public TextType CauseOfActionCode
        {
            get
            {
                return this.causeOfActionCode;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CauseOfActionCode");
                }
                if ((this.causeOfActionCode != value))
                {
                    this.causeOfActionCode = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4, ElementName = "CaseContestedIndicator")]
        public Boolean CaseContestedIndicator
        {
            get
            {
                return this.caseContestedIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CaseContestedIndicator");
                }
                if ((this.caseContestedIndicator != value))
                {
                    this.caseContestedIndicator = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DomesticCasePerson", Order = 5)]
        public System.Collections.Generic.List<Oasis.LegalXml.CourtFiling.v40.Ecf.PersonType> DomesticCasePerson
        {
            get
            {
                return this.domesticCasePerson;
            }
            set
            {
                if ((this.domesticCasePerson != value))
                {
                    this.domesticCasePerson = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6, ElementName = "DomesticCaseViolencePetition")]
        public DomesticCaseViolencePetitionType DomesticCaseViolencePetition
        {
            get
            {
                return this.domesticCaseViolencePetition;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("DomesticCaseViolencePetition");
                }
                if ((this.domesticCaseViolencePetition != value))
                {
                    this.domesticCaseViolencePetition = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DomesticCaseChildSupportPetition", Order = 7)]
        public System.Collections.Generic.List<DomesticCaseChildSupportPetitionType> DomesticCaseChildSupportPetition
        {
            get
            {
                return this.domesticCaseChildSupportPetition;
            }
            set
            {
                if ((this.domesticCaseChildSupportPetition != value))
                {
                    this.domesticCaseChildSupportPetition = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DomesticCaseOrder", Order = 8)]
        public System.Collections.Generic.List<DomesticCaseOrderType> DomesticCaseOrder
        {
            get
            {
                return this.domesticCaseOrder;
            }
            set
            {
                if ((this.domesticCaseOrder != value))
                {
                    this.domesticCaseOrder = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("MarriageAssociation", Order = 9)]
        public System.Collections.Generic.List<MarriageAssociationType> MarriageAssociation
        {
            get
            {
                return this.marriageAssociation;
            }
            set
            {
                if ((this.marriageAssociation != value))
                {
                    this.marriageAssociation = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "DomesticCaseChildSupportPetitionType")]
    [System.Xml.Serialization.XmlRootAttribute("DomesticCaseChildSupportPetition", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "DomesticCaseChildSupportPetition")]
    public partial class DomesticCaseChildSupportPetitionType : ComplexObjectType
    {
        private System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> immediateFamilyAssociation;
        private TextType jurisdictionReasonText;

        public DomesticCaseChildSupportPetitionType()
        {
        }

        public DomesticCaseChildSupportPetitionType(System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> immediateFamilyAssociation, TextType jurisdictionReasonText)
        {
            this.immediateFamilyAssociation = immediateFamilyAssociation;
            this.jurisdictionReasonText = jurisdictionReasonText;
        }

        [System.Xml.Serialization.XmlElementAttribute("ImmediateFamilyAssociation", Namespace = "http://niem.gov/niem/niem-core/2.0", IsNullable = true, Order = 0)]
        public System.Collections.Generic.List<Niem.NiemCore.v20.ImmediateFamilyAssociationType> ImmediateFamilyAssociation
        {
            get
            {
                return this.immediateFamilyAssociation;
            }
            set
            {
                if ((this.immediateFamilyAssociation != value))
                {
                    this.immediateFamilyAssociation = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1, ElementName = "JurisdictionReasonText")]
        public TextType JurisdictionReasonText
        {
            get
            {
                return this.jurisdictionReasonText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("JurisdictionReasonText");
                }
                if ((this.jurisdictionReasonText != value))
                {
                    this.jurisdictionReasonText = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "DomesticCaseObligationType")]
    [System.Xml.Serialization.XmlRootAttribute("DomesticCaseObligation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "DomesticCaseObligation")]
    public partial class DomesticCaseObligationType : Niem.NiemCore.v20.ObligationRecurrenceType
    {
        private System.Collections.Generic.List<FinancialObligationType> financialObligation;

        public DomesticCaseObligationType()
        {
        }

        public DomesticCaseObligationType(System.Collections.Generic.List<FinancialObligationType> financialObligation)
        {
            this.financialObligation = financialObligation;
        }

        [System.Xml.Serialization.XmlElementAttribute("FinancialObligation", Order = 0)]
        public System.Collections.Generic.List<FinancialObligationType> FinancialObligation
        {
            get
            {
                return this.financialObligation;
            }
            set
            {
                if ((this.financialObligation != value))
                {
                    this.financialObligation = value;
                }
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "DomesticCaseOrderType")]
    [System.Xml.Serialization.XmlRootAttribute("DomesticCaseOrder", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "DomesticCaseOrder")]
    public partial class DomesticCaseOrderType : Niem.Domains.Jxdm.v40.CourtOrderType
    {

        private TextType domesticCaseOrderTypeText;
        private TextType courtFindingsText;
        private System.Collections.Generic.List<DomesticCaseObligationType> domesticCaseObligation;

        public DomesticCaseOrderType()
        {
        }

        public DomesticCaseOrderType(TextType domesticCaseOrderTypeText, TextType courtFindingsText, System.Collections.Generic.List<DomesticCaseObligationType> domesticCaseObligation)
        {
            this.domesticCaseOrderTypeText = domesticCaseOrderTypeText;
            this.courtFindingsText = courtFindingsText;
            this.domesticCaseObligation = domesticCaseObligation;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0, ElementName = "DomesticCaseOrderTypeText")]
        public TextType DomesticCaseOrderTypeText
        {
            get
            {
                return this.domesticCaseOrderTypeText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("DomesticCaseOrderTypeText");
                }
                if ((this.domesticCaseOrderTypeText != value))
                {
                    this.domesticCaseOrderTypeText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1, ElementName = "CourtFindingsText")]
        public TextType CourtFindingsText
        {
            get
            {
                return this.courtFindingsText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CourtFindingsText");
                }
                if ((this.courtFindingsText != value))
                {
                    this.courtFindingsText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("DomesticCaseObligation", Order = 2)]
        public System.Collections.Generic.List<DomesticCaseObligationType> DomesticCaseObligation
        {
            get
            {
                return this.domesticCaseObligation;
            }
            set
            {
                if ((this.domesticCaseObligation != value))
                {
                    this.domesticCaseObligation = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "DomesticCaseViolencePetitionType")]
    [System.Xml.Serialization.XmlRootAttribute("DomesticCaseViolencePetition", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "DomesticCaseViolencePetitionType")]
    public partial class DomesticCaseViolencePetitionType : ComplexObjectType
    {

        private TextType requestToVacateCode;
        private TextType requestToVacateText;
        private TextType stayawayDistanceText;
        private TextType noContactCode;
        private TextType custodyDescriptionText;
        private TextType childSupportText;
        private Boolean respondentDangerAlertIndicator;

        public DomesticCaseViolencePetitionType()
        {
        }

        public DomesticCaseViolencePetitionType(TextType requestToVacateCode, TextType requestToVacateText, TextType stayawayDistanceText, TextType noContactCode, TextType custodyDescriptionText, TextType childSupportText, Boolean respondentDangerAlertIndicator)
        {
            this.requestToVacateCode = requestToVacateCode;
            this.requestToVacateText = requestToVacateText;
            this.stayawayDistanceText = stayawayDistanceText;
            this.noContactCode = noContactCode;
            this.custodyDescriptionText = custodyDescriptionText;
            this.childSupportText = childSupportText;
            this.respondentDangerAlertIndicator = respondentDangerAlertIndicator;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0, ElementName = "RequestToVacateCode")]
        public TextType RequestToVacateCode
        {
            get
            {
                return this.requestToVacateCode;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("RequestToVacateCode");
                }
                if ((this.requestToVacateCode != value))
                {
                    this.requestToVacateCode = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1, ElementName = "RequestToVacateText")]
        public TextType RequestToVacateText
        {
            get
            {
                return this.requestToVacateText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("RequestToVacateText");
                }
                if ((this.requestToVacateText != value))
                {
                    this.requestToVacateText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "StayawayDistanceText")]
        public TextType StayawayDistanceText
        {
            get
            {
                return this.stayawayDistanceText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("StayawayDistanceText");
                }
                if ((this.stayawayDistanceText != value))
                {
                    this.stayawayDistanceText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3, ElementName = "NoContactCode")]
        public TextType NoContactCode
        {
            get
            {
                return this.noContactCode;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("NoContactCode");
                }
                if ((this.noContactCode != value))
                {
                    this.noContactCode = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4, ElementName = "CustodyDescriptionText")]
        public TextType CustodyDescriptionText
        {
            get
            {
                return this.custodyDescriptionText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("CustodyDescriptionText");
                }
                if ((this.custodyDescriptionText != value))
                {
                    this.custodyDescriptionText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5, ElementName = "ChildSupportText")]
        public TextType ChildSupportText
        {
            get
            {
                return this.childSupportText;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ChildSupportText");
                }
                if ((this.childSupportText != value))
                {
                    this.childSupportText = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6, ElementName = "RespondentDangerAlertIndicator")]
        public Boolean RespondentDangerAlertIndicator
        {
            get
            {
                return this.respondentDangerAlertIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("RespondentDangerAlertIndicator");
                }
                if ((this.respondentDangerAlertIndicator != value))
                {
                    this.respondentDangerAlertIndicator = value;
                }
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "FinancialObligationType")]
    [System.Xml.Serialization.XmlRootAttribute("FinancialObligation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "FinancialObligationType")]
    public partial class FinancialObligationType : Niem.NiemCore.v20.ObligationType
    {

        private System.Collections.Generic.List<AmountType> obligationPaymentAmount;
        private Boolean obligationIncomeAttachedIndicator;
        private Boolean obligationStateDisbursementIndicator;

        public FinancialObligationType()
        {
        }

        public FinancialObligationType(System.Collections.Generic.List<AmountType> obligationPaymentAmount, Boolean obligationIncomeAttachedIndicator, Boolean obligationStateDisbursementIndicator)
        {
            this.obligationPaymentAmount = obligationPaymentAmount;
            this.obligationIncomeAttachedIndicator = obligationIncomeAttachedIndicator;
            this.obligationStateDisbursementIndicator = obligationStateDisbursementIndicator;
        }

        [System.Xml.Serialization.XmlElementAttribute("ObligationPaymentAmount", Order = 0)]
        public System.Collections.Generic.List<AmountType> ObligationPaymentAmount
        {
            get
            {
                return this.obligationPaymentAmount;
            }
            set
            {
                if ((this.obligationPaymentAmount != value))
                {
                    this.obligationPaymentAmount = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1, ElementName = "ObligationIncomeAttachedIndicator")]
        public Boolean ObligationIncomeAttachedIndicator
        {
            get
            {
                return this.obligationIncomeAttachedIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ObligationIncomeAttachedIndicator");
                }
                if ((this.obligationIncomeAttachedIndicator != value))
                {
                    this.obligationIncomeAttachedIndicator = value;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2, ElementName = "ObligationStateDisbursementIndicator")]
        public Boolean ObligationStateDisbursementIndicator
        {
            get
            {
                return this.obligationStateDisbursementIndicator;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("ObligationStateDisbursementIndicator");
                }
                if ((this.obligationStateDisbursementIndicator != value))
                {
                    this.obligationStateDisbursementIndicator = value;
                }
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3074")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", TypeName = "MarriageAssociationType")]
    [System.Xml.Serialization.XmlRootAttribute("MarriageAssociation", Namespace = "urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:DomesticCase-4.0", IsNullable = false, ElementName = "MarriageAssociationType")]
    public partial class MarriageAssociationType : Niem.NiemCore.v20.PersonUnionAssociationType
    {

        private Niem.Domains.Screeing.v20.MarriageAssociationAugmentationType marriageAssociationAugmentation;

        public MarriageAssociationType()
        {
        }

        public MarriageAssociationType(Niem.Domains.Screeing.v20.MarriageAssociationAugmentationType marriageAssociationAugmentation)
        {
            this.marriageAssociationAugmentation = marriageAssociationAugmentation;
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://niem.gov/niem/domains/screening/2.0", Order = 0, ElementName = "MarriageAssociationAugmentation")]
        public Niem.Domains.Screeing.v20.MarriageAssociationAugmentationType MarriageAssociationAugmentation
        {
            get
            {
                return this.marriageAssociationAugmentation;
            }
            set
            {
                if ((value == null))
                {
                    throw new System.ArgumentNullException("MarriageAssociationAugmentation");
                }
                if ((this.marriageAssociationAugmentation != value))
                {
                    this.marriageAssociationAugmentation = value;
                }
            }
        }
    }

}
